I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 67, in script
    N "Main Menu Time"
Exception: Sayer 'N' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 67, in script
    N "Main Menu Time"
  File "C:\Users\azcun\Downloads\renpy-8.2.1-sdk.7z\renpy-8.2.1-sdk\renpy\ast.py", line 2557, in execute
    Say.execute(self)
  File "C:\Users\azcun\Downloads\renpy-8.2.1-sdk.7z\renpy-8.2.1-sdk\renpy\ast.py", line 575, in execute
    who = eval_who(self.who, self.who_fast)
  File "C:\Users\azcun\Downloads\renpy-8.2.1-sdk.7z\renpy-8.2.1-sdk\renpy\ast.py", line 464, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'N' is not defined.

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.1.24030407
The Exhibition 1.0
Fri May 17 15:55:50 2024
